### ISSUE TITLE
GitHub card

### ISSUE THREAD

**Issue by mohitkyadav** [mohitkyadav/coolme#1]
Generate a embedded GitHub card for username.

~Fields : **Thumbnail, repos, stars, forks, bio, followers/following, contri streak**~
**Make org links clickable**

**Comment by mohitkyadav** [comment]
@aashutoshrathi still waiting...

**Comment by aashutoshrathi** [comment]
Will do ASAP.

**Comment by mohitkyadav** [comment]
Richembed class supports markdown, `[org](link)`
