### ISSUE TITLE
add instructions for env variables to readme

### ISSUE THREAD

**Issue by mohitkyadav** [mohitkyadav/coolme#22]

**Comment by sarbikbetal** [comment]
@mohitkyadav I want to work on this, but where do I get a list of all the environment variables being used?

**Comment by mohitkyadav** [comment]
you can search `process.env` in the project

**Comment by sarbikbetal** [comment]
Alright I'll do that.😄

**Comment by sarbikbetal** [comment]
I've figure out everything except `MAGNET_URI` and `HORRIBLE_URI`, could you help me with those?

**Comment by mohitkyadav** [comment]
@sarbikbetal don't need include these. not mandatory

**Comment by sarbikbetal** [comment]
Alright thanks 😊
